version: '3.7'

services:
  mongo:
    image: mongo:4.1
    restart: always
    volumes:
      - mdb-data:/data/db

  formio:
    build: 
      context: ./
      args:
        ROOT_EMAIL: ${ROOT_EMAIL}
        ROOT_PASSWORD: ${ROOT_PASSWORD}
    restart: always
    links:
      - mongo
    ports:
      - "3001:3001"
    external_links:
      - mongo
    environment:
      NODE_CONFIG: "{\"mongo\": \"${MONGODB_URL}\"}"
      ROOT_EMAIL: ${ROOT_EMAIL}
      ROOT_PASSWORD: ${ROOT_PASSWORD}

volumes:
  mdb-data:
